### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-final-saraalite#1]
Muy buen trabajo @saraalite!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 310 / 429
- [ ] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `title`.
- [ ] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `alt`.
- [ ] HTML > HAMBURGUESA: El menú de la hamburguesa debe tener un `nav`.
- [x] HTML > HERO: El texto del título del hero debe ser: Anonymous proxy.
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips".
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Looking through a window".
- [ ] HTML > MÓDULO LOOKING: Debe haber un `a` o un `button` con el texto "Go".
- [ ] HTML > MÓDULO 3 REASON: Debe haber un elemento con el texto "Ut sed metus".
- [ ] HTML > MÓDULO 3 REASON: Debe haber un `a` o un `button` con el texto "More reasons".
- [ ] HTML > FOOTER: Debe haber un `a` con el texto "Mastodon.social".
- [x] HTML > FOOTER: Necesitamos ocho `li` dentro de los `ul`.
- [ ] HTML > FOOTER: Necesitamos ocho `a` dentro de los `li`.

- [x] CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > `order`.
- [ ] CSS > TRANSICIONES: Debemos usar alguna transición CSS.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by saraalite** [comment]
¡Hola! 
Me gustaría comentar y preguntar un par de cosillas que me confunden después de ver los issues.

-En primer lugar tengo dudas con los atributos title y alt. Creí entender en clase (seguramente sea fallo mío) que había que incluirlos cuando la imagen no era decorativa, por eso yo solo los he puesto en la imagen del hero, que es la que más peso me parecía tener. Pensé que no era necesario meterlos en los iconos.

-El texto de mi título es Anonymous Proxy, pero imitando a María en el ejercicio de los bomberos lo dividí en dos span para poder manejarlo en bloques.

-También tengo un texto "Insomnia tips" y "Looking through a window" (este último también en un <span> para poder manejarlo mejor y dejarlo tal cual mostraba la maquetadora en Zeplin.

-Tengo divididos los 'li' dentro de los 'ul' según aparecían en maquetación (5 en la columna article y 3 en social).

-He puesto los 'li' dentro de los 'a' en lugar de los 'a' dentro de los 'li', no sé si afecta mucho, pero me parecía que así se hacía más fácil a la hora de interactuar con el enlace.

-Tengo dos elementos en el footer (maquetado con flex) con la propiedad 'order'.

-He usado las transiciones que se sugerían y una animación en el botón del footer.

¡Muchas gracias! :)

**Comment by migueldelmazo** [comment]
Hola @saraalite, te contesto:

-En primer lugar tengo dudas con los atributos title y alt. Creí entender en clase (seguramente sea fallo mío) que había que incluirlos cuando la imagen no era decorativa, por eso yo solo los he puesto en la imagen del hero, que es la que más peso me parecía tener. Pensé que no era necesario meterlos en los iconos: **tienes toda la razón, no lo cambies**.

-El texto de mi título es Anonymous Proxy, pero imitando a María en el ejercicio de los bomberos lo dividí en dos span para poder manejarlo en bloques: **No está mal dividirlo en span. Pero hay que poner "Anonymous proxy". La "A" en mayúsculas y el resto en minúsculas, es decir, gramaticalmente bien, como si lo escribieras en un documento de texto. Si abres esta página https://www.google.com/search?q=adalab&oq=adalab&aqs=chrome.0.69i59j0l2j69i60l5.2638j0j7&sourceid=chrome&ie=UTF-8 verás los contenidos de la página de Adalab, sin los estilos de la página de Adalab. Si en la página de Adalab ponemos "Inclusión laboral de las mujeres en la tecnología. Consigue trabajo gracias a nuestros" todo en minúsuculas en Google se vería mal.**

-También tengo un texto "Insomnia tips" y "Looking through a window" (este último también en un para poder manejarlo mejor y dejarlo tal cual mostraba la maquetadora en Zeplin: **este lo mismo del anterior**.

-Tengo divididos los 'li' dentro de los 'ul' según aparecían en maquetación (5 en la columna article y 3 en social): Los hijos directos de un UL solo pueden ser LI. Tú tienes UL > A > LI  y debería ser UL > LI > A. Esto si es importante que lo recuerdes.

-He puesto los 'li' dentro de los 'a' en lugar de los 'a' dentro de los 'li', no sé si afecta mucho, pero me parecía que así se hacía más fácil a la hora de interactuar con el enlace.

-Tengo dos elementos en el footer (maquetado con flex) con la propiedad 'order': fallo mío, déjalo como está.

-He usado las transiciones que se sugerían y una animación en el botón del footer: pues tienes razón. No entiendo por qué ha fallado el bot. Voy a comprobarlo!!!

Gracias por currarte las mejoras.

**Comment by saraalite** [comment]
Muchas gracias por contestar, lo de Anonymous Proxy me tenía confundida porque en la anterior evaluación me saltó la máquina y decía que tenía que utilizar text transform capitalize y ahora lo pongo en todo para no equivocarme otra vez con lo mismo. ¡Gracias!
